name = "pvtor_frontend"
version = "1.0.0"
target = "javascript"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
lustre = ">= 5.5.2 and < 6.0.0"
rsvp = ">= 1.2.0 and < 2.0.0"
varasto = ">= 3.0.2 and < 4.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
plinth = ">= 0.9.2 and < 1.0.0"
tempo = ">= 0.4.4 and < 1.0.0"
gtz = ">= 0.3.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 2.3.4 and < 3.0.0"
